on: [push]
name: build image

env:
  DEBIAN_FRONTEND: noninteractive
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@master

      - name: Install dependencies
        run: |
            apt-get -y update && \
            apt-get -y install --no-install-recommends \
              git vim parted \
              quilt coreutils qemu-user-static debootstrap zerofree zip dosfstools \
              libarchive-tools libcap2-bin rsync grep udev xz-utils curl xxd file kmod bc\
              binfmt-support ca-certificates qemu-utils kpartx fdisk gpg pigz && \
              rm -rf /var/lib/apt/lists/*
      
      - name: Clone
        working-directory: ../
        run: git clone git@github.com:RPi-Distro/pi-gen.git

      - name: Disable stage 3, 4 & 5
        working-directory: ../pi-gen 
        run: |
          touch ./stage3/SKIP ./stage4/SKIP ./stage5/SKIP
          touch ./stage4/SKIP_IMAGES ./stage5/SKIP_IMAGES

      - name: Copy config
        working-directory: ../pi-gen 
        run: ../pi-gen_stage4.5-cutiepi/config ./config

      - name: Run build
        working-directory: ../pi-gen 
        run: ./build.sh
        